#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")

docker build .. --no-cache -t airlab 
yes | docker image prune || true

docker_run () {
    docker run \
           --volume $PWD/../src:/airlab/src\
           --volume $PWD/../examples:/airlab/examples \
           --volume $PWD/../SubmodularMaximization.jl:/airlab/ \
           airlab \
           "$@"
}
