#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")

./build

docker run \
       --volume $PWD/../src:/airlab/src\
       --volume $PWD/../examples:/airlab/examples \
       --volume $PWD/../SubmodularMaximization.jl:/airlab/SubmodularMaximization.jl \
       -it \
       -p 8888:8888 \
       airlab \
       jupyter notebook --notebook-dir /airlab --ip 0.0.0.0 --no-browser --allow-root

