#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")


sudo docker run \
       --volume $PWD/../src:/airlab/src \
       --volume $PWD/../experiments:/airlab/experiments \
       --volume $PWD/../examples:/airlab/examples \
       --volume $PWD/../SubmodularMaximization.jl:/airlab/SubmodularMaximization.jl \
       --env DISPLAY=$DISPLAY \
       --volume /tmp/.X11-unix:/tmp/.X11-unix \
       --volume $HOME/.Xauthority:$HOME/.Xauthority \
       -it \
       -p 8888:8888 \
       airlab \
       jupyter notebook --notebook-dir /airlab --ip 0.0.0.0 --no-browser --allow-root

