#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd $(dirname "$0")

# ./build

sudo docker run \
       --volume $PWD/../src:/airlab/src \
       --volume $PWD/../blender:/airlab/blender \
       --volume $PWD/../experiments:/airlab/experiments \
       --volume $PWD/../examples:/airlab/examples \
       --volume $PWD/../SubmodularMaximization.jl:/airlab/SubmodularMaximization.jl \
       --env DISPLAY=$DISPLAY \
       --volume /tmp/.X11-unix:/tmp/.X11-unix \
       --volume $HOME/.Xauthority:$HOME/.Xauthority \
       -it \
       airlab \
       /bin/bash
